### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/apex_parser2#1]
* [x] if
* [x] else if
* [x] else
* [x] for
* [x] while
* [x] SOQL
  * [x] CSV adapter
  * [x] JSON adapter
* [x] new
* [x] return value
* [x] argument binding
* [x] call instance method
* [x] call static method
* [x] add line_number
* [x] add/sub/mul/div
* [x] array syntax
* [x] List/Map class
* [x] generics
* [x] trigger
* [ ] module/ファイル整理
* [ ] gem化
* [x] 別ファイル読み込み
* [x] new Hoge().aaa();
* [ ] extends
* [ ] interface
* [ ] abstract
* [ ] private
* [ ] protected
* [x] commentout
* [x] getter, setter
* [ ] ApexPages.currentPage().getParameters().get('')
* [ ] Date
* [ ] URL.getSalesforceBaseUrl()
* [ ] HTTPRequest
* [ ] XMLStreamReader
* [ ] Crypto
* [ ] XMLStreamWriter
* [ ] Base64Encode/Decode
